
# Sleep and Doomscrolling Habits Analysis

## Deliverable 2: Reproducible Python Workflow

This notebook analyzes a synthetic dataset of 1,000 individuals to explore the relationship between doomscrolling habits, screen time, and sleep patterns.

**Data Source:** Kaggle - Sleep & Doomscrolling Habits Dataset

### Stakeholders

**Primary Stakeholders: Young Adults and College Students**

The primary stakeholders are young adults and college students who may benefit from understanding the relationship between doomscrolling habits and sleep quality. The analysis aims to present the findings through clear, accessible, and easy-to-understand visualizations.

**Secondary Stakeholders:**
- **University counselors:** Use the findings to support student discussions about sleep and well-being.
- **Health educators:** Promote awareness of healthy bedtime habits.
- **Sleep specialists:** Explore patterns between screen habits and sleep outcomes.
- **Researchers:** Investigate digital wellness and potential relationships between doomscrolling and sleep quality.


**Objective:** To prepare, clean, validate, and transform the dataset for visualization and analysis.

In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:

# Step 1: Import the dataset

df = pd.read_csv("sleep_doomscrolling_habits.csv")

# Display the first 5 rows
df.head()

,respondent_id,age,bedtime_screen_time_minutes,total_daily_screen_time_hours,doomscroll_sessions_per_night,avg_doomscroll_session_minutes,sleep_hours_per_night,sleep_latency_minutes,number_of_night_wakeups,caffeine_intake_mg_per_day,...,occupation_status,country_region,primary_device_used_at_night,bedtime_routine_type,uses_night_mode,keeps_phone_in_bedroom,consumes_negative_news_content,uses_sleep_tracking_app,doomscroller,sleep_quality_category
0,D30000,22,13.0,1.85,2,5.4,8.1,19.0,2,155.0,...,Unemployed,Germany,Tablet,Meditation/Journaling,Yes,Yes,Yes,No,Yes,Good
1,D30001,18,90.0,3.61,3,29.6,7.0,31.0,3,82.0,...,Student,India,Smartphone,Meditation/Journaling,No,Yes,Yes,No,Yes,Poor
2,D30002,37,51.0,5.15,3,15.5,7.1,24.0,2,49.0,...,Student,India,Laptop,Reading,No,Yes,No,Yes,Yes,Fair
3,D30003,27,53.0,3.74,0,51.4,8.4,35.0,0,42.0,...,NaN,United States,Smartphone,No Fixed Routine,No,Yes,Yes,No,No,Fair
4,D30004,17,67.0,6.09,2,32.2,7.2,19.0,1,76.0,...,Employed Part-time,United States,Smartphone,Watching Videos,No,No,No,No,No,Fair

In [3]:

# Check the number of rows and columns

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 1000
,Number of columns: 30

In [4]:

# Check column names, data types, and non-null values
df.info()

<class 'pandas.DataFrame'>
,RangeIndex: 1000 entries, 0 to 999
,Data columns (total 30 columns):
, #   Column                          Non-Null Count  Dtype
,---  ------                          --------------  -----
, 0   respondent_id                   1000 non-null   str
, 1   age                             1000 non-null   int64
, 2   bedtime_screen_time_minutes     1000 non-null   float64
, 3   total_daily_screen_time_hours   1000 non-null   float64
, 4   doomscroll_sessions_per_night   1000 non-null   int64
, 5   avg_doomscroll_session_minutes  1000 non-null   float64
, 6   sleep_hours_per_night           1000 non-null   float64
, 7   sleep_latency_minutes           1000 non-null   float64
, 8   number_of_night_wakeups         1000 non-null   int64
, 9   caffeine_intake_mg_per_day      950 non-null    float64
, 10  anxiety_score                   1000 non-null   int64
, 11  stress_score                    1000 non-null   int64
, 12  sleep_quality_score             960 non-null    float64
, 13  daytime_fatigue_score           1000 non-null   int64
, 14  number_of_news_apps_used        1000 non-null   int64
, 15  phone_checks_per_night          1000 non-null   int64
, 16  exercise_minutes_per_day        950 non-null    float64
, 17  days_since_last_digital_detox   1000 non-null   float64
, 18  weekly_sleep_debt_hours         1000 non-null   float64
, 19  gender                          1000 non-null   str
, 20  occupation_status               970 non-null    str
, 21  country_region                  1000 non-null   str
, 22  primary_device_used_at_night    970 non-null    str
, 23  bedtime_routine_type            980 non-null    str
, 24  uses_night_mode                 1000 non-null   str
, 25  keeps_phone_in_bedroom          1000 non-null   str
, 26  consumes_negative_news_content  1000 non-null   str
, 27  uses_sleep_tracking_app         1000 non-null   str
, 28  doomscroller                    1000 non-null   str
, 29  sleep_quality_category          1000 non-null   str
,dtypes: float64(10), int64(8), str(12)
,memory usage: 307.6 KB

In [5]:

# Check missing values in each column
df.isnull().sum()

respondent_id                      0
age                                0
bedtime_screen_time_minutes        0
total_daily_screen_time_hours      0
doomscroll_sessions_per_night      0
avg_doomscroll_session_minutes     0
sleep_hours_per_night              0
sleep_latency_minutes              0
number_of_night_wakeups            0
caffeine_intake_mg_per_day        50
anxiety_score                      0
stress_score                       0
sleep_quality_score               40
daytime_fatigue_score              0
number_of_news_apps_used           0
phone_checks_per_night             0
exercise_minutes_per_day          50
days_since_last_digital_detox      0
weekly_sleep_debt_hours            0
gender                             0
occupation_status                 30
country_region                     0
primary_device_used_at_night      30
bedtime_routine_type              20
uses_night_mode                    0
keeps_phone_in_bedroom             0
consumes_negative_news_content     0
uses_sleep_tracking_app            0
doomscroller                       0
sleep_quality_category             0
dtype: int64

In [6]:

# Count duplicate rows
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 0

In [7]:

# Display descriptive statistics
df.describe()

,age,bedtime_screen_time_minutes,total_daily_screen_time_hours,doomscroll_sessions_per_night,avg_doomscroll_session_minutes,sleep_hours_per_night,sleep_latency_minutes,number_of_night_wakeups,caffeine_intake_mg_per_day,anxiety_score,stress_score,sleep_quality_score,daytime_fatigue_score,number_of_news_apps_used,phone_checks_per_night,exercise_minutes_per_day,days_since_last_digital_detox,weekly_sleep_debt_hours
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,950.000000,1000.000000,1000.000000,960.000000,1000.000000,1000.000000,1000.000000,950.000000,1000.00000,1000.000000
mean,27.309000,50.111000,3.664670,2.037000,24.924800,7.415200,27.882000,1.412000,120.752632,4.644000,6.147000,4.828125,5.978000,1.371000,2.479000,53.282105,41.58000,4.864100
std,7.495312,31.328136,1.923755,1.586237,12.487106,0.765751,14.510225,1.172019,81.978478,1.792338,1.892346,0.475292,1.760857,1.177602,1.588736,21.158850,39.15437,4.649553
min,15.000000,1.000000,1.000000,0.000000,1.000000,4.000000,2.000000,0.000000,3.000000,1.000000,1.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000
25%,21.750000,27.000000,2.230000,1.000000,16.700000,6.900000,18.000000,1.000000,61.000000,3.000000,5.000000,5.000000,5.000000,0.000000,1.000000,39.000000,13.00000,0.275000
50%,27.000000,44.000000,3.345000,2.000000,22.600000,7.400000,27.000000,1.000000,102.000000,5.000000,6.000000,5.000000,6.000000,1.000000,2.000000,54.000000,32.00000,3.900000
75%,33.000000,66.000000,4.785000,3.000000,30.925000,7.900000,37.000000,2.000000,166.000000,6.000000,8.000000,5.000000,7.000000,2.000000,3.250000,69.000000,57.25000,7.825000
max,54.000000,225.000000,12.950000,10.000000,90.000000,9.800000,90.000000,6.000000,600.000000,10.000000,10.000000,5.000000,10.000000,7.000000,9.000000,124.000000,276.00000,29.400000


### Data Inspection

The dataset contains 1,000 records and 30 variables. Data inspection was performed to identify variable types, missing values, duplicate records, and descriptive statistics. These checks help assess the dataset's quality and determine which cleaning operations are required before analysis.


## 3. Data Validation

This section checks whether the dataset contains the required columns, unique respondent IDs, and valid numerical values before cleaning.

In [8]:

# Check if all required columns exist

required_columns = [
    "respondent_id",
    "doomscroller",
    "sleep_hours_per_night",
    "bedtime_screen_time_minutes",
    "sleep_latency_minutes",
    "avg_doomscroll_session_minutes",
    "country_region",
    "sleep_quality_category"
]

missing_columns = [
    col for col in required_columns
    if col not in df.columns
]

print("Missing required columns:", missing_columns)

Missing required columns: []

In [9]:

# Check for duplicate respondent IDs

print("Duplicate respondent IDs:",
      df["respondent_id"].duplicated().sum())

Duplicate respondent IDs: 0

In [10]:

# Check for invalid negative values

print("Negative sleep hours:",
      (df["sleep_hours_per_night"] < 0).sum())

print("Negative bedtime screen time:",
      (df["bedtime_screen_time_minutes"] < 0).sum())

print("Negative sleep latency:",
      (df["sleep_latency_minutes"] < 0).sum())

print("Negative doomscroll session duration:",
      (df["avg_doomscroll_session_minutes"] < 0).sum())

Negative sleep hours: 0
,Negative bedtime screen time: 0
,Negative sleep latency: 0
,Negative doomscroll session duration: 0

In [ ]:
# Additional Section 3 checks: missing values, category consistency, and potential outliers

print("\n--- Missing Values Before Cleaning ---")
missing_before = df.isnull().sum()
print(missing_before[missing_before > 0])

print("\n--- Duplicate Row Check ---")
print("Duplicate rows:", df.duplicated().sum())

# Check negative values across available numeric lifestyle and sleep variables.
numeric_check_columns = [
    "sleep_hours_per_night",
    "bedtime_screen_time_minutes",
    "sleep_latency_minutes",
    "avg_doomscroll_session_minutes",
    "caffeine_intake_mg_per_day",
    "exercise_minutes_per_day"
]
print("\n--- Negative Value Checks ---")
for col in numeric_check_columns:
    if col in df.columns:
        print(f"{col}: {(df[col] < 0).sum()}")

# Review categorical values and detect leading/trailing spaces.
categorical_check_columns = [
    "doomscroller",
    "sleep_quality_category",
    "country_region",
    "occupation_status",
    "primary_device_used_at_night",
    "bedtime_routine_type"
]
print("\n--- Category and Whitespace Checks ---")
for col in categorical_check_columns:
    if col in df.columns:
        print(f"\n{col} values:")
        print(df[col].value_counts(dropna=False))
        if df[col].dtype == "object":
            values = df[col].dropna().astype(str)
            extra_spaces = (values != values.str.strip()).sum()
            print("Values with leading/trailing spaces:", extra_spaces)

# Flag possible outliers using the IQR rule; do not automatically remove them.
outlier_check_columns = [
    "sleep_hours_per_night",
    "bedtime_screen_time_minutes",
    "sleep_latency_minutes",
    "avg_doomscroll_session_minutes",
    "caffeine_intake_mg_per_day",
    "exercise_minutes_per_day"
]
outlier_results = []
for col in outlier_check_columns:
    if col in df.columns:
        values = df[col].dropna()
        if not values.empty:
            q1 = values.quantile(0.25)
            q3 = values.quantile(0.75)
            iqr = q3 - q1
            lower_bound = q1 - 1.5 * iqr
            upper_bound = q3 + 1.5 * iqr
            count = int(((values < lower_bound) | (values > upper_bound)).sum())
            outlier_results.append({
                "Variable": col,
                "Lower Bound": lower_bound,
                "Upper Bound": upper_bound,
                "Potential Outliers": count
            })

print("\n--- Potential Outliers (IQR Rule) ---")
display(pd.DataFrame(outlier_results))
print("Potential outliers are flagged for review and are not automatically removed.")


### Validation Checks

The dataset was validated by checking the presence of required columns, duplicate respondent identifiers and rows, negative numerical values, missing values, categorical value consistency, and potential outliers using the IQR rule. Potential outliers are flagged for review and are not automatically removed. These checks help assess whether the dataset is suitable for cleaning and further analysis.


## 4. Data Cleaning

This section prepares the dataset for analysis by creating a copy of the original data, checking missing values, and applying appropriate cleaning methods. The original dataset remains unchanged.

In [11]:

# Create a copy of the original dataset

df_clean = df.copy()

print("Original dataset:", df.shape)
print("Working copy:", df_clean.shape)

Original dataset: (1000, 30)
,Working copy: (1000, 30)

In [12]:

# Show columns with missing values

missing_values = df_clean.isnull().sum()

print(missing_values[missing_values > 0])

caffeine_intake_mg_per_day      50
,sleep_quality_score             40
,exercise_minutes_per_day        50
,occupation_status               30
,primary_device_used_at_night    30
,bedtime_routine_type            20
,dtype: int64

In [13]:

# Fill missing numerical lifestyle values using the median

df_clean["caffeine_intake_mg_per_day"] = (
    df_clean["caffeine_intake_mg_per_day"].fillna(
        df_clean["caffeine_intake_mg_per_day"].median()
    )
)

df_clean["exercise_minutes_per_day"] = (
    df_clean["exercise_minutes_per_day"].fillna(
        df_clean["exercise_minutes_per_day"].median()
    )
)

print("Numerical lifestyle columns cleaned!")

Numerical lifestyle columns cleaned!

In [14]:

# Fill missing categorical values with Unknown

categorical_columns = [
    "occupation_status",
    "primary_device_used_at_night",
    "bedtime_routine_type"
]

for col in categorical_columns:
    df_clean[col] = df_clean[col].fillna("Unknown")

print("Categorical columns cleaned!")

Categorical columns cleaned!

In [15]:

# Check remaining missing values

print("Missing values after cleaning:")

print(
    df_clean.isnull().sum()[
        df_clean.isnull().sum() > 0
    ]
)

Missing values after cleaning:
,sleep_quality_score    40
,dtype: int64


### Missing Value Treatment

Missing numerical values in caffeine intake and daily exercise were replaced using median imputation. Missing categorical values in occupation status, primary device used at night, and bedtime routine were labelled as "Unknown".

The 40 missing sleep quality scores were retained to avoid introducing artificial outcome values. The cleaning operations were performed on a working copy, preserving the original dataset.


## 5. Data Integration

This project uses one approved data source: the Sleep & Doomscrolling Habits Dataset from Kaggle.

All required variables for the proposed visualizations are included in the same CSV file. Therefore, no external data merging or joining is necessary.

The cleaned dataset will be used directly for data preparation and transformations.

In [16]:

# Verify the cleaned dataset is ready

print("Cleaned dataset dimensions:", df_clean.shape)
print("Number of data sources used:", 1)

df_clean.head()

Cleaned dataset dimensions: (1000, 30)
,Number of data sources used: 1

,respondent_id,age,bedtime_screen_time_minutes,total_daily_screen_time_hours,doomscroll_sessions_per_night,avg_doomscroll_session_minutes,sleep_hours_per_night,sleep_latency_minutes,number_of_night_wakeups,caffeine_intake_mg_per_day,...,occupation_status,country_region,primary_device_used_at_night,bedtime_routine_type,uses_night_mode,keeps_phone_in_bedroom,consumes_negative_news_content,uses_sleep_tracking_app,doomscroller,sleep_quality_category
0,D30000,22,13.0,1.85,2,5.4,8.1,19.0,2,155.0,...,Unemployed,Germany,Tablet,Meditation/Journaling,Yes,Yes,Yes,No,Yes,Good
1,D30001,18,90.0,3.61,3,29.6,7.0,31.0,3,82.0,...,Student,India,Smartphone,Meditation/Journaling,No,Yes,Yes,No,Yes,Poor
2,D30002,37,51.0,5.15,3,15.5,7.1,24.0,2,49.0,...,Student,India,Laptop,Reading,No,Yes,No,Yes,Yes,Fair
3,D30003,27,53.0,3.74,0,51.4,8.4,35.0,0,42.0,...,Unknown,United States,Smartphone,No Fixed Routine,No,Yes,Yes,No,No,Fair
4,D30004,17,67.0,6.09,2,32.2,7.2,19.0,1,76.0,...,Employed Part-time,United States,Smartphone,Watching Videos,No,No,No,No,No,Fair


## 6. Data Preparation and Transformations

This section prepares the cleaned dataset for the three visualizations proposed in Deliverable 1:

1. Average Sleep Hours by Doomscrolling Status
2. Bedtime Screen Time vs. Sleep Latency
3. Short and Long Doomscrolling Sessions by Country/Region

In [17]:

# Chart 1: Average sleep hours by doomscrolling status

sleep_summary = (
    df_clean.groupby("doomscroller")["sleep_hours_per_night"]
    .mean()
    .reset_index()
)

sleep_summary

  doomscroller  sleep_hours_per_night
0           No               7.533015
1          Yes               7.285504

In [18]:

# Chart 2: Bedtime screen time vs. sleep latency

scatter_data = df_clean[
    [
        "bedtime_screen_time_minutes",
        "sleep_latency_minutes",
        "sleep_quality_category"
    ]
].dropna()

scatter_data.head()

   bedtime_screen_time_minutes  sleep_latency_minutes sleep_quality_category
0                         13.0                   19.0                   Good
1                         90.0                   31.0                   Poor
2                         51.0                   24.0                   Fair
3                         53.0                   35.0                   Fair
4                         67.0                   19.0                   Fair

In [19]:

# Chart 3: Classify short and long doomscrolling sessions

SESSION_THRESHOLD = 15

# Keep missing durations unclassified
df_clean["session_category"] = np.where(
    df_clean["avg_doomscroll_session_minutes"].isna(),
    "Unknown",
    np.where(
        df_clean["avg_doomscroll_session_minutes"] <= SESSION_THRESHOLD,
        "Short",
        "Long"
    )
)

# Count session categories by region
region_summary = pd.crosstab(
    df_clean["country_region"],
    df_clean["session_category"]
)

region_summary

session_category  Long  Short
country_region
Australia           49     14
Brazil              41     12
Canada              68     13
Germany             49     12
India              211     59
Nigeria             50     11
Philippines         68     13
UAE                 35     11
United Kingdom      83     16
United States      151     34


## 7. Data Export

This section exports the cleaned dataset and three visualization-ready tables as CSV files. The exported files allow the analysis to be reused and reproduced without modifying the original dataset.

In [20]:

# Create a folder for exported files

from pathlib import Path

output_folder = Path("output")
output_folder.mkdir(exist_ok=True)

print("Output folder created successfully!")

Output folder created successfully!

In [21]:

# Export the cleaned dataset
df_clean.to_csv(
    output_folder / "cleaned_sleep_data.csv",
    index=False
)

# Export Chart 1 data
sleep_summary.to_csv(
    output_folder / "sleep_summary.csv",
    index=False
)

# Export Chart 2 data
scatter_data.to_csv(
    output_folder / "scatter_data.csv",
    index=False
)

# Export Chart 3 data
region_summary.to_csv(
    output_folder / "region_summary.csv"
)

print("All CSV files exported successfully!")

All CSV files exported successfully!

In [22]:

# Verify the exported files exist

for file in output_folder.glob("*.csv"):
    print(file.name, "-", file.stat().st_size, "bytes")

cleaned_sleep_data.csv - 158172 bytes
,region_summary.csv - 190 bytes
,scatter_data.csv - 16028 bytes
,sleep_summary.csv - 81 bytes


## 8. Reproducibility Instructions

### Input
- File: `sleep_doomscrolling_habits.csv`
- Source: Kaggle – Sleep & Doomscrolling Habits Dataset
- Format: CSV
- Dataset size: 1,000 rows and 30 columns
- Data type: Synthetic (simulated)

### Python Dependencies
The workflow requires:
- Python 3
- pandas
- numpy
- matplotlib
- Jupyter Notebook

### Execution Order
1. Import the required Python libraries.
2. Load the original CSV dataset.
3. Inspect the data structure, missing values, and duplicates.
4. Validate required columns, unique identifiers, and numerical values.
5. Create a copy and clean missing values.
6. Confirm that no external data integration is required.
7. Prepare three visualization-ready datasets.
8. Export cleaned and transformed data into CSV files.

Run all notebook cells from top to bottom.

### Parameters
- Doomscrolling session threshold: 15 minutes.
- Short session: 15 minutes or less.
- Long session: More than 15 minutes.
- Missing numerical lifestyle values: Median imputation.
- Missing categorical values: Labelled as "Unknown".
- Missing sleep quality scores: Retained as missing.

The 15-minute threshold is an analytical assumption and should be approved by the project group.

### Outputs
The workflow creates an `output` folder containing:

- `cleaned_sleep_data.csv`
- `sleep_summary.csv`
- `scatter_data.csv`
- `region_summary.csv`

### Reproducibility
The original CSV file and Jupyter Notebook must be saved in the same project folder. The original dataset remains unchanged, and all transformations are applied to a separate working copy.